# Generated by Django 4.1.4 on 2022-12-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
